extends RefCounted
class_name FighterCharacterLife

## Runtime personality multipliers + presentation strings for each fighter.
## Keeps shared GLB clips but differentiates timing, pose, aura, and selection copy.

const PROFILES := {
	"ember-vale": {
		"display": "Ember Vale",
		"personality": ["Intense", "Confident", "Forward"],
		"fantasy": "Close the gap as heat.",
		"line": "Pressure first. Apologize never.",
		"idle_speed": 1.18,
		"run_speed": 1.12,
		"attack_speed": 1.2,
		"lean": -0.08,
		"aura_shape": "tongues",
		"aura_pulse": 1.4,
		"expression_idle": "confident",
		"expression_charge": "charging",
		"expression_hurt": "strained",
		"victory_pose": "proud_fist",
		"defeat_pose": "kneel_guard",
		"throw_style": "blast",
		"select_archetype": "Rushdown",
		"power_id": "Controlled Fire",
	},
	"rook-ironside": {
		"display": "Rook Ironside",
		"personality": ["Stable", "Protective", "Deliberate"],
		"fantasy": "Be the wall.",
		"line": "Plant. Hold. Shatter.",
		"idle_speed": 0.72,
		"run_speed": 0.82,
		"attack_speed": 0.85,
		"lean": 0.04,
		"aura_shape": "rings",
		"aura_pulse": 0.7,
		"expression_idle": "focused",
		"expression_charge": "focused",
		"expression_hurt": "strained",
		"victory_pose": "fist_heart",
		"defeat_pose": "kneel_upright",
		"throw_style": "slam",
		"select_archetype": "Tank",
		"power_id": "Iron Guard",
	},
	"juno-spark": {
		"display": "Juno Spark",
		"personality": ["Quick", "Mischievous", "Electric"],
		"fantasy": "Think three beats ahead.",
		"line": "Blink once. You're late.",
		"idle_speed": 1.35,
		"run_speed": 1.28,
		"attack_speed": 1.32,
		"lean": -0.05,
		"aura_shape": "arcs",
		"aura_pulse": 1.8,
		"expression_idle": "confident",
		"expression_charge": "surprised",
		"expression_hurt": "hurt",
		"victory_pose": "snap_spin",
		"defeat_pose": "hips_annoyed",
		"throw_style": "yank",
		"select_archetype": "Glass Cannon",
		"power_id": "Arc Impulse",
	},
	"kaia-windrow": {
		"display": "Kaia Windrow",
		"personality": ["Graceful", "Free", "Calm"],
		"fantasy": "Own the air.",
		"line": "Wind never asks permission.",
		"idle_speed": 0.95,
		"run_speed": 1.05,
		"attack_speed": 1.0,
		"lean": -0.02,
		"aura_shape": "ribbons",
		"aura_pulse": 1.0,
		"expression_idle": "neutral",
		"expression_charge": "focused",
		"expression_hurt": "surprised",
		"victory_pose": "lifted_arms",
		"defeat_pose": "soft_kneel",
		"throw_style": "lift",
		"select_archetype": "Aerial",
		"power_id": "Sky Current",
	},
	"nix-calder": {
		"display": "Nix Calder",
		"personality": ["Composed", "Precise", "Cold"],
		"fantasy": "Win without raising your voice.",
		"line": "Precision is louder than shouting.",
		"idle_speed": 0.68,
		"run_speed": 0.9,
		"attack_speed": 0.92,
		"lean": 0.0,
		"aura_shape": "crystals",
		"aura_pulse": 0.55,
		"expression_idle": "focused",
		"expression_charge": "charging",
		"expression_hurt": "hurt",
		"victory_pose": "subtle_nod",
		"defeat_pose": "compose",
		"throw_style": "pin",
		"select_archetype": "Zoning",
		"power_id": "Frost Lattice",
	},
	"orion-vell": {
		"display": "Orion Vell",
		"personality": ["Curious", "Authoritative", "Cosmic"],
		"fantasy": "Move like gravity obeys you.",
		"line": "Orbits wait for intention.",
		"idle_speed": 0.8,
		"run_speed": 0.88,
		"attack_speed": 0.95,
		"lean": 0.02,
		"aura_shape": "orbit",
		"aura_pulse": 1.1,
		"expression_idle": "confident",
		"expression_charge": "charging",
		"expression_hurt": "strained",
		"victory_pose": "arms_open",
		"defeat_pose": "kneel_compose",
		"throw_style": "orbit",
		"select_archetype": "Power",
		"power_id": "Gravity Well",
	},
	"vesper-nyx": {
		"display": "Vesper Nyx",
		"personality": ["Mysterious", "Dangerous", "Deceptive"],
		"fantasy": "Strike where they look last.",
		"line": "Shadows don't telegraph.",
		"idle_speed": 1.08,
		"run_speed": 1.1,
		"attack_speed": 1.15,
		"lean": -0.06,
		"aura_shape": "smoke",
		"aura_pulse": 1.25,
		"expression_idle": "confident",
		"expression_charge": "focused",
		"expression_hurt": "hurt",
		"victory_pose": "smirk",
		"defeat_pose": "fade_kneel",
		"throw_style": "vanish",
		"select_archetype": "Mix-up",
		"power_id": "Eclipse Veil",
	},
}


static func for_id(fighter_id: String) -> Dictionary:
	if PROFILES.has(fighter_id):
		return PROFILES[fighter_id].duplicate(true)
	return {
		"display": fighter_id,
		"personality": ["Unknown"],
		"fantasy": "",
		"line": "Ready.",
		"idle_speed": 1.0,
		"run_speed": 1.0,
		"attack_speed": 1.0,
		"lean": 0.0,
		"aura_shape": "orb",
		"aura_pulse": 1.0,
		"expression_idle": "neutral",
		"expression_charge": "charging",
		"expression_hurt": "hurt",
		"victory_pose": "proud_fist",
		"defeat_pose": "kneel_guard",
		"throw_style": "blast",
		"select_archetype": "Balanced",
		"power_id": "Aura",
	}
