export const APP_VERSION_LABEL = "Anime Aggressors Pages Build";
export const APP_EXPECTED_MODES = [
  "Play Match",
  "Create Fighter",
  "Custom Game",
  "Career",
  "Match History",
  "Replay Vault",
  "Saved Games",
  "Fighter Stats",
  "Controls",
  "Training Mode",
  "Impact Dummy Derby",
  "Flagline Clash",
  "Controller Test",
  "Rollback Debug",
  "Edge-IO Lab",
  "Prototype Lab",
  "Feedback",
] as const;
