"""v7 review packet. Pair shots are staged by the renderer, not attacker-only."""
from __future__ import annotations

# label, action, frame, preset, silhouette, grayscale, outline, aim, pair, vfx, emission_off
PACKET = (
    ("front", "", 1, "FRONT_ORTHO", False, False, False, "", False, False, False),
    ("front_3q", "", 1, "FRONT_3Q", False, False, False, "", False, False, False),
    ("front_3q_color", "idle", 1, "FRONT_3Q", False, False, False, "", False, False, False),
    ("front_3q_grayscale", "idle", 1, "FRONT_3Q", False, True, False, "", False, False, False),
    ("side", "", 1, "SIDE", False, False, False, "", False, False, False),
    ("back", "", 1, "BACK", False, False, False, "", False, False, False),
    ("select_preview", "idle", 1, "FRONT_3Q", False, False, True, "", False, False, False),
    ("gameplay_scale", "idle", 1, "GAMEPLAY_LEFT", False, False, False, "", False, False, False),
    ("gameplay_color", "idle", 1, "GAMEPLAY_LEFT", False, False, False, "", False, False, False),
    ("gameplay_grayscale", "idle", 1, "GAMEPLAY_LEFT", False, True, False, "", False, False, False),
    ("emission_off", "idle", 1, "FRONT_ORTHO", False, False, False, "", False, False, True),
    ("head_detail", "idle", 1, "DETAIL_HEAD", False, False, True, "head", False, False, False),
    ("glove_fist", "idle", 1, "DETAIL_HANDS", False, False, False, "glove", False, False, False),
    ("glove_open", "personality_idle", 8, "DETAIL_HANDS", False, False, False, "glove", False, False, False),
    ("boot_detail", "idle", 1, "DETAIL_FEET", False, False, False, "boot", False, False, False),
    ("costume_detail", "idle", 1, "DETAIL_COSTUME", False, False, False, "costume", False, False, False),
    ("grayscale_values", "idle", 1, "FRONT_ORTHO", False, True, False, "", False, False, True),
    ("silhouette_idle", "idle", 1, "SILHOUETTE", True, False, False, "", False, False, False),
    ("silhouette_super", "signature_lane_finisher", 16, "SILHOUETTE", True, False, False, "", False, False, False),
    ("idle", "idle", 1, "FRONT_3Q", False, False, False, "", False, False, False),
    ("walk", "walk", 8, "FRONT_3Q", False, False, False, "", False, False, False),
    ("run", "run", 6, "GAMEPLAY_LEFT", False, False, False, "", False, False, False),
    ("dash", "dash", 4, "GAMEPLAY_LEFT", False, False, False, "", False, False, False),
    ("charge_0_off", "idle", 1, "FRONT_3Q", False, False, False, "", False, False, True),
    ("charge_100_off", "charged_idle", 12, "FRONT_3Q", False, False, False, "", False, False, True),
    ("charge_100_on", "charged_idle", 12, "FRONT_3Q", False, False, False, "", False, True, False),
    ("heavy_precontact_pair", "heavy", 4, "FRONT_3Q", False, False, False, "pair", True, False, False),
    ("heavy_contact_pair_off", "heavy", 11, "FRONT_3Q", False, False, False, "pair", True, False, False),
    ("heavy_contact_pair_on", "heavy", 11, "FRONT_3Q", False, False, False, "pair", True, True, False),
    ("heavy_follow", "heavy", 16, "FRONT_3Q", False, False, False, "pair", True, False, False),
    ("hurt_peak_no_knockback", "hurt_heavy", 6, "FRONT_3Q", False, False, False, "", False, False, False),
    ("launch_start", "hurt_heavy", 10, "FRONT_3Q", False, False, False, "", False, False, False),
    ("super_off", "signature_lane_finisher", 16, "FRONT_3Q", False, False, False, "", False, False, True),
    ("super_on", "signature_lane_finisher", 16, "FRONT_3Q", False, False, False, "", False, True, False),
    ("clash_start", "clash_lock", 2, "FRONT_3Q", False, False, False, "pair", True, False, False),
    ("clash_lock", "clash_lock", 12, "FRONT_3Q", False, False, False, "pair", True, False, False),
    ("clash_push", "clash_lock", 16, "FRONT_3Q", False, False, False, "pair", True, False, False),
    ("clash_win", "clash_lock", 20, "FRONT_3Q", False, False, False, "pair", True, False, False),
    ("clash_lose", "clash_lock", 8, "FRONT_3Q", False, False, False, "pair", True, False, False),
    ("KO", "ko", 12, "FRONT_3Q", False, False, False, "", False, False, False),
)

REQUIRED_SHOTS = tuple(row[0] for row in PACKET)

ROSTER_SHEETS = (
    "select_lineup",
    "color_lineup",
    "grayscale_lineup",
    "silhouettes",
    "gloves",
    "boots",
    "masks",
    "hero_features",
    "idle_identities",
    "heavy_pairs",
    "hurt_peaks",
    "charge_transformation",
    "supers",
    "clash_presets",
    "value_groups",
)
