"""Shared 161-move V3 constants. Original Anime Aggressors language only."""

from __future__ import annotations

REQUIRED_MOVES = [
    "jab_1",
    "jab_2",
    "jab_finisher",
    "forward_tilt",
    "up_tilt",
    "down_tilt",
    "dash_attack",
    "heavy_attack",
    "neutral_air",
    "forward_air",
    "up_air",
    "down_air",
    "neutral_special_projectile",
    "side_special",
    "up_special_recovery",
    "down_special",
    "grab",
    "throw_forward",
    "throw_back",
    "throw_up",
    "throw_down",
    "aura_charge",
    "aura_burst",
]

FIGHTERS = [
    "ember-vale",
    "rook-ironside",
    "juno-spark",
    "kaia-windrow",
    "nix-calder",
    "orion-vell",
    "vesper-nyx",
]

NON_MOVE_STATES = [
    "idle",
    "idle_variant",
    "walk",
    "run",
    "turn",
    "jump_start",
    "jump_rise",
    "jump_apex",
    "fall",
    "land",
    "crouch",
    "shield_start",
    "shield_hold",
    "shield_release",
    "dodge_forward",
    "dodge_back",
    "air_dodge",
    "grab_hold",
    "grab_break",
    "hurt_light",
    "hurt_medium",
    "hurt_heavy",
    "launched",
    "tumble",
    "critical_launch",
    "ledge_grab",
    "ledge_hang",
    "ledge_getup",
    "ledge_jump",
    "ledge_drop",
    "ko",
    "respawn",
    "victory",
    "defeat",
    "aura_charge",
    "aura_level_1",
    "aura_level_2",
    "aura_level_3",
    "aura_ready",
    "aura_burst",
]

# Existing clip used as the retarget source for a new dedicated clip.
NEW_MOVE_CLIP_SOURCES = {
    "dash_attack": "dash",
    "side_special": "signature_lane_feint",
    "down_special": "signature_lane_trap",
    "aura_burst": "signature_lane_burst",
}

NEW_STATE_CLIP_SOURCES = {
    "idle_variant": "idle",
    "turn": "walk",
    "jump_start": "jump",
    "jump_rise": "jump",
    "jump_apex": "jump",
    "land": "landing",
    "crouch": "shield",
    "shield_start": "shield",
    "shield_hold": "shield",
    "shield_release": "shield",
    "dodge_forward": "dodge",
    "dodge_back": "dodge",
    "grab_hold": "grab",
    "grab_break": "grab",
    "hurt_light": "hurt",
    "hurt_medium": "hurt",
    "hurt_heavy": "hurt",
    "launched": "launch",
    "critical_launch": "launch",
    "ledge_grab": "idle",
    "ledge_hang": "idle",
    "ledge_getup": "jump",
    "ledge_jump": "jump",
    "ledge_drop": "fall",
    "respawn": "aura_charge",
    "aura_level_1": "aura_charge",
    "aura_level_2": "aura_charge",
    "aura_level_3": "aura_charge",
    "aura_ready": "aura_charge",
}

FIGHTER_META = {
    "ember-vale": {
        "display": "Ember Vale",
        "element": "flame",
        "thesis": "Flame rushdown",
        "particle": "ember_flame_heat",
        "vfx_family": "flame_tongues",
        "tone": 220.0,
        "synth": "fire",
        "mix_bus": "combat_ember",
        "bible_body": "humanoid flame being; red core, orange flame body, hot-yellow highlights",
    },
    "rook-ironside": {
        "display": "Rook Ironside",
        "element": "impact",
        "thesis": "Impact bruiser",
        "particle": "dust_chips_fracture",
        "vfx_family": "impact_ring",
        "tone": 110.0,
        "synth": "earth",
        "mix_bus": "combat_rook",
        "bible_body": "massive forged/stone humanoid; orange-amber impact seams, dark iron structure",
    },
    "juno-spark": {
        "display": "Juno Spark",
        "element": "volt",
        "thesis": "Volt speed-confirm",
        "particle": "sparks_arcs_nodes",
        "vfx_family": "jagged_arc",
        "tone": 330.0,
        "synth": "electric",
        "mix_bus": "combat_juno",
        "bible_body": "yellow-gold electricity body with dark conductive structure and cyan-white current",
    },
    "kaia-windrow": {
        "display": "Kaia Windrow",
        "element": "gale",
        "thesis": "Gale aerial spacer",
        "particle": "air_streaks_crescents",
        "vfx_family": "wind_ribbon",
        "tone": 262.0,
        "synth": "wind",
        "mix_bus": "combat_kaia",
        "bible_body": "true-green wind body, teal/mint currents and air-white edges",
    },
    "nix-calder": {
        "display": "Nix Calder",
        "element": "frost",
        "thesis": "Frost control tank",
        "particle": "snow_frost_crystal",
        "vfx_family": "crystal_lance",
        "tone": 196.0,
        "synth": "frost",
        "mix_bus": "combat_nix",
        "bible_body": "true-blue ice body, dark cold core and frost-white/cyan crystal edges",
    },
    "orion-vell": {
        "display": "Orion Vell",
        "element": "gravity",
        "thesis": "Gravity combo control",
        "particle": "constellation_orbit_nodes",
        "vfx_family": "constellation_nodes",
        "tone": 147.0,
        "synth": "gravity",
        "mix_bus": "combat_orion",
        "bible_body": "indigo/midnight cosmic body with star-white constellation nodes",
    },
    "vesper-nyx": {
        "display": "Vesper Nyx",
        "element": "void",
        "thesis": "Void phase trickster",
        "particle": "phase_motes_void_wisps",
        "vfx_family": "void_seam",
        "tone": 185.0,
        "synth": "shadow",
        "mix_bus": "combat_vesper",
        "bible_body": "violet/void-plum body with pale phase edges; translucency only while phasing",
    },
}

MOVE_FANTASY = {
    "ember-vale": {
        "jab_1": "Quick ignition knuckle with a small ember trail",
        "jab_2": "Cross-body flame palm with a hotter impact layer",
        "jab_finisher": "Close-range furnace burst ending the jab string",
        "forward_tilt": "Flame-edge forearm sweep with a short crescent",
        "up_tilt": "Rising flare uppercut forming a narrow anti-air column",
        "down_tilt": "Low searing sweep leaving a brief ground flame lick",
        "dash_attack": "Heatline shoulder/forearm rush with body flame streaming backward",
        "heavy_attack": "Committed furnace hammer with a large ignition at contact",
        "neutral_air": "Compact corona spin wrapping the body in flame",
        "forward_air": "Flame-propelled forward kick with a sharp contact burst",
        "up_air": "Updraft flare kick/palm that pops targets above Ember",
        "down_air": "Meteor ember stomp with a downward flame cone",
        "neutral_special_projectile": "Cinder shot to wider flame wave to multi-hit flame stream",
        "side_special": "Blazing rush/reposition strike built around movement and pressure",
        "up_special_recovery": "Jet-flare ascent with visible propulsion and vulnerable recovery",
        "down_special": "Flashpoint guard/counter or short ignition trap",
        "grab": "Heated clinch; flame wrap after confirmed grab",
        "throw_forward": "Flame spin toss",
        "throw_back": "Reversal kick into flame burst",
        "throw_up": "Erupting uppercut",
        "throw_down": "Ground ignition bounce",
        "aura_charge": "Furnace-heart charge; flames intensify from the body core outward",
        "aura_burst": "Rushing eruption / explosive flame surge",
    },
    "rook-ironside": {
        "jab_1": "Short armored body jab with a dense thud",
        "jab_2": "Heavy cross with visible mass and limited travel",
        "jab_finisher": "Two-hand/shoulder impact producing a compact quake ring",
        "forward_tilt": "Forearm battering ram with a brief armor window",
        "up_tilt": "Rising stone/iron uppercut with debris flecks",
        "down_tilt": "Low stomp/sweep creating a tight fracture line",
        "dash_attack": "Momentum shoulder charge with high commitment",
        "heavy_attack": "Seismic hammer strike; higher aura adds an aftershock",
        "neutral_air": "Compact armored body spin using Rook's mass",
        "forward_air": "Forward double-fist/shoulder smash",
        "up_air": "Upward armored head/forearm lift",
        "down_air": "Crater drop with heavy landing emphasis",
        "neutral_special_projectile": "Short-range shockwave; never a long-range zoning bullet",
        "side_special": "Armored quake rush / command-impact approach",
        "up_special_recovery": "Impact-assisted rising leap with limited steering",
        "down_special": "Brace/fortify stance rewarding a read",
        "grab": "Command-grab style armored capture",
        "throw_forward": "Shoulder carry slam",
        "throw_back": "Suplex reversal",
        "throw_up": "Rising boulder launcher",
        "throw_down": "Crater slam",
        "aura_charge": "Forge-pressure charge; seams glow and Rook feels denser",
        "aura_burst": "Seismic burst with pressure ring and controlled debris",
    },
    "juno-spark": {
        "jab_1": "Fast electric fingertip/palm strike",
        "jab_2": "Rapid follow-up elbow/kick with a current bridge",
        "jab_finisher": "Short chain-lightning snap confirming the string",
        "forward_tilt": "Linear voltage palm/thrust with quick recovery",
        "up_tilt": "Rising arc lash above Juno",
        "down_tilt": "Low current sweep creating a brief confirm window",
        "dash_attack": "Blink-speed lunge with electric afterimage",
        "heavy_attack": "Charged rail-punch/heel focused on precision",
        "neutral_air": "Radial static pulse multi-hit around the body",
        "forward_air": "Fast aerial spear-kick with electric needle trail",
        "up_air": "Forked lightning kick/palm upward",
        "down_air": "Downward voltage spike with a narrow line",
        "neutral_special_projectile": "Fast electric needle; aura increases speed and chain",
        "side_special": "Conductive dash-cancel / electric rush",
        "up_special_recovery": "Lightning-step ascent with directional burst",
        "down_special": "Magnetic pull/push pulse or brief bounded stun field",
        "grab": "Electromagnetic snare/clinch",
        "throw_forward": "Electric palm launch",
        "throw_back": "Blink-behind kick",
        "throw_up": "Lightning launcher",
        "throw_down": "Stun bounce",
        "aura_charge": "Capacitor charge; current routes through the limbs",
        "aura_burst": "Flash-circuit burst enabling speed/confirm payoff",
    },
    "kaia-windrow": {
        "jab_1": "Short palm gust",
        "jab_2": "Crosswind backhand with slight push",
        "jab_finisher": "Compact cyclone pop resetting spacing",
        "forward_tilt": "Wind-slash crescent",
        "up_tilt": "Vertical pressure blade / air scoop",
        "down_tilt": "Low gust sweep with reposition push",
        "dash_attack": "Slipstream dash strike",
        "heavy_attack": "Compressed-air cleave with a readable wind blade",
        "neutral_air": "Orbiting air ring / gentle multi-hit vortex",
        "forward_air": "Forward wind-blade kick/slash",
        "up_air": "Rising current fan for anti-air control",
        "down_air": "Descending pressure dive with a controlled gust burst",
        "neutral_special_projectile": "Curving wind blade; aura allows bend, return or linger",
        "side_special": "Crosswind surfing dash / wind-lane reposition",
        "up_special_recovery": "Cyclone lift with strong vertical control",
        "down_special": "Wind buffer/barrier that redirects or pushes",
        "grab": "Pressure-current capture",
        "throw_forward": "Gust push",
        "throw_back": "Crosswind reversal",
        "throw_up": "Cyclone lift",
        "throw_down": "Tornado pop-up",
        "aura_charge": "Air gathers in layered spirals; movement posture lightens",
        "aura_burst": "Spiral-current burst controlling a large airspace moment",
    },
    "nix-calder": {
        "jab_1": "Cold short punch with frost fleck",
        "jab_2": "Ice-coated follow-up strike",
        "jab_finisher": "Crystal-break burst creating brief space",
        "forward_tilt": "Ice-arm blade/shard swing",
        "up_tilt": "Rising icicle / ice-arm uppercut",
        "down_tilt": "Low frost sweep adding chill",
        "dash_attack": "Sliding glacier shoulder with controlled friction trail",
        "heavy_attack": "Large ice hammer / wall-break strike",
        "neutral_air": "Snow-crystal orbit giving defensive spacing",
        "forward_air": "Ice-spear limb extension",
        "up_air": "Upward shard fan",
        "down_air": "Heavy icicle drop/stomp",
        "neutral_special_projectile": "Ice shard; higher aura becomes thicker shard/wall-control",
        "side_special": "Ice-lane slide or advancing wall shove",
        "up_special_recovery": "Ice-pillar rise / frost lift with readable recovery",
        "down_special": "Ice wall/trap/armor state — stage-control signature",
        "grab": "Freeze-lock clinch",
        "throw_forward": "Frozen shove",
        "throw_back": "Ice pivot toss",
        "throw_up": "Glacier pillar",
        "throw_down": "Freeze-bury setup",
        "aura_charge": "Cold concentrates; snow/frost motes accumulate",
        "aura_burst": "Glacier-lock burst with crystal wall/fracture language",
    },
    "orion-vell": {
        "jab_1": "Short vector tap subtly biasing target position",
        "jab_2": "Second gravity-assisted strike pulling toward Orion",
        "jab_finisher": "Repulsion pop sending the target along an authored combo angle",
        "forward_tilt": "Vector shove with a narrow distortion lane",
        "up_tilt": "Gravity-lift palm for controlled anti-air",
        "down_tilt": "Low weight-field sweep altering footing/launch",
        "dash_attack": "Gravity-assisted glide strike",
        "heavy_attack": "Compressed-mass blow with delayed pressure collapse",
        "neutral_air": "Orbiting gravity nodes around Orion",
        "forward_air": "Repulsion palm in the air",
        "up_air": "Suspension pulse above the body",
        "down_air": "Weight-drop spike with gravity-well contact",
        "neutral_special_projectile": "Slow gravity orb with pull field",
        "side_special": "Attract/repel vector step for spacing and route control",
        "up_special_recovery": "Gravity-inversion ascent with controlled vector steering",
        "down_special": "Open gravity sphere/well briefly controlling space",
        "grab": "Gravity-suspension capture",
        "throw_forward": "Gravitational shove",
        "throw_back": "Orbit reversal",
        "throw_up": "Suspended juggle launch",
        "throw_down": "Gravity-crush bounce",
        "aura_charge": "Constellation nodes brighten/orbit and local distortion builds",
        "aura_burst": "Orbit-collapse burst bending launch/space",
    },
    "vesper-nyx": {
        "jab_1": "Quick phase-in strike",
        "jab_2": "Cross-up hand/heel appearing from an offset",
        "jab_finisher": "Delayed void pop after the visible strike",
        "forward_tilt": "Phase-blade / void-edge sweep",
        "up_tilt": "Vertical shadow tear",
        "down_tilt": "Low shadow-slip strike with reposition",
        "dash_attack": "Null-step cross-through attack",
        "heavy_attack": "Delayed rift cleave with a clear startup marker",
        "neutral_air": "Phase halo alternating present/absent timing",
        "forward_air": "Ghosted forward strike with afterimage",
        "up_air": "Portal/void lift slash",
        "down_air": "Phase-drop spike appearing just before contact",
        "neutral_special_projectile": "Delayed void mark / trap orb",
        "side_special": "Phase-step / cross-up teleport cancel with strict readability",
        "up_special_recovery": "Portal/phase ascent with a visible destination tell",
        "down_special": "Clone/afterimage or void-trap misdirection",
        "grab": "Phase-bind capture",
        "throw_forward": "Void push",
        "throw_back": "Phase swap",
        "throw_up": "Portal launcher",
        "throw_down": "Void trap plant",
        "aura_charge": "Void haze with pale edge separation; silhouette stays readable",
        "aura_burst": "Null-step burst with multi-position phase echo",
    },
}

MOVE_CLASS = {
    "jab_1": "light",
    "jab_2": "light",
    "jab_finisher": "medium",
    "forward_tilt": "medium",
    "up_tilt": "medium",
    "down_tilt": "medium",
    "dash_attack": "medium",
    "heavy_attack": "heavy",
    "neutral_air": "medium",
    "forward_air": "medium",
    "up_air": "medium",
    "down_air": "heavy",
    "neutral_special_projectile": "medium",
    "side_special": "heavy",
    "up_special_recovery": "medium",
    "down_special": "heavy",
    "grab": "light",
    "throw_forward": "medium",
    "throw_back": "medium",
    "throw_up": "medium",
    "throw_down": "medium",
    "aura_charge": "aura",
    "aura_burst": "super",
}

HITSTOP_TARGET = {
    "light": {"min": 2, "max": 3},
    "medium": {"min": 4, "max": 6},
    "heavy": {"min": 7, "max": 10},
    "aura": {"min": 10, "max": 13},
    "super": {"min": 13, "max": 16},
}

VFX_SHAPE = {
    "ember-vale": "flame_tongue_cone",
    "rook-ironside": "pressure_ring_fracture",
    "juno-spark": "jagged_fork_arc",
    "kaia-windrow": "crescent_ribbon",
    "nix-calder": "crystal_shard_fan",
    "orion-vell": "orbit_node_collapse",
    "vesper-nyx": "phase_seam_echo",
}

THROW_OFFSETS = {
    "ember-vale": {
        "throw_forward": {"x": 24, "y": -10},
        "throw_back": {"x": -26, "y": -8},
        "throw_up": {"x": 6, "y": -30},
        "throw_down": {"x": 10, "y": 14},
    },
    "rook-ironside": {
        "throw_forward": {"x": 30, "y": -6},
        "throw_back": {"x": -32, "y": -4},
        "throw_up": {"x": 8, "y": -36},
        "throw_down": {"x": 12, "y": 18},
    },
    "juno-spark": {
        "throw_forward": {"x": 22, "y": -12},
        "throw_back": {"x": -28, "y": -10},
        "throw_up": {"x": 2, "y": -34},
        "throw_down": {"x": 6, "y": 12},
    },
    "kaia-windrow": {
        "throw_forward": {"x": 28, "y": -14},
        "throw_back": {"x": -30, "y": -12},
        "throw_up": {"x": 0, "y": -38},
        "throw_down": {"x": 8, "y": 10},
    },
    "nix-calder": {
        "throw_forward": {"x": 26, "y": -8},
        "throw_back": {"x": -24, "y": -6},
        "throw_up": {"x": 4, "y": -32},
        "throw_down": {"x": 10, "y": 16},
    },
    "orion-vell": {
        "throw_forward": {"x": 20, "y": -16},
        "throw_back": {"x": -22, "y": -14},
        "throw_up": {"x": 0, "y": -40},
        "throw_down": {"x": 4, "y": 8},
    },
    "vesper-nyx": {
        "throw_forward": {"x": 18, "y": -12},
        "throw_back": {"x": -34, "y": -10},
        "throw_up": {"x": -4, "y": -36},
        "throw_down": {"x": 14, "y": 12},
    },
}
