import type { MoveFrameData } from "../frameData.js";

/** Shared platform-fighter move taxonomy (Milestone 3). */
export type CombatMoveCategory =
  | "jab"
  | "forwardTilt"
  | "upTilt"
  | "downTilt"
  | "dashAttack"
  | "neutralAir"
  | "forwardAir"
  | "backAir"
  | "upAir"
  | "downAir"
  | "neutralSpecial"
  | "sideSpecial"
  | "upSpecial"
  | "downSpecial"
  | "grab"
  | "pummel"
  | "forwardThrow"
  | "backThrow"
  | "upThrow"
  | "downThrow"
  | "spotDodge"
  | "roll"
  | "airDodge";

export type CombatMoveData = MoveFrameData & {
  id: string;
  label: string;
  category: CombatMoveCategory;
  angleDeg: number;
  shieldDamage: number;
  shieldStunFrames: number;
  hitboxWidth: number;
  hitboxHeight: number;
  hitboxOffsetX: number;
  hitboxOffsetY: number;
  groundedOnly?: boolean;
  airborneOnly?: boolean;
  hitIntervalFrames?: number;
  canHitSameTargetAgain?: boolean;
  landingLagOverride?: number;
};

function move(
  partial: Omit<CombatMoveData, "cancelWindows"> & { cancelWindows?: number[] },
): CombatMoveData {
  return {
    cancelWindows: [],
    ...partial,
  };
}

/** Default catalog — all fighters share these until per-character kits exist. */
export const DEFAULT_MOVE_CATALOG: Record<string, CombatMoveData> = {
  neutral_attack: move({
    id: "neutral_attack",
    label: "Jab",
    category: "jab",
    move: "neutral_attack",
    startup: 4,
    active: 3,
    recovery: 10,
    damage: 3,
    baseKnockback: 4,
    knockbackGrowth: 1.05,
    hitstop: 3,
    angleDeg: 45,
    shieldDamage: 2,
    shieldStunFrames: 6,
    hitboxWidth: 40,
    hitboxHeight: 28,
    hitboxOffsetX: 32,
    hitboxOffsetY: 48,
    groundedOnly: true,
  }),
  forward_attack: move({
    id: "forward_attack",
    label: "Forward Tilt",
    category: "forwardTilt",
    move: "forward_attack",
    startup: 5,
    active: 3,
    recovery: 12,
    damage: 7,
    baseKnockback: 8,
    knockbackGrowth: 1.2,
    hitstop: 5,
    angleDeg: 30,
    shieldDamage: 5,
    shieldStunFrames: 8,
    hitboxWidth: 48,
    hitboxHeight: 32,
    hitboxOffsetX: 36,
    hitboxOffsetY: 48,
    groundedOnly: true,
  }),
  up_attack: move({
    id: "up_attack",
    label: "Up Tilt",
    category: "upTilt",
    move: "up_attack",
    startup: 6,
    active: 4,
    recovery: 14,
    damage: 8,
    baseKnockback: 9,
    knockbackGrowth: 1.2,
    hitstop: 6,
    angleDeg: 80,
    shieldDamage: 6,
    shieldStunFrames: 9,
    hitboxWidth: 40,
    hitboxHeight: 44,
    hitboxOffsetX: 0,
    hitboxOffsetY: 56,
    groundedOnly: true,
  }),
  down_attack: move({
    id: "down_attack",
    label: "Down Tilt",
    category: "downTilt",
    move: "down_attack",
    startup: 4,
    active: 3,
    recovery: 10,
    damage: 5,
    baseKnockback: 6,
    knockbackGrowth: 1.1,
    hitstop: 4,
    angleDeg: -20,
    shieldDamage: 4,
    shieldStunFrames: 7,
    hitboxWidth: 44,
    hitboxHeight: 28,
    hitboxOffsetX: 28,
    hitboxOffsetY: 36,
    groundedOnly: true,
  }),
  dash_attack: move({
    id: "dash_attack",
    label: "Dash Attack",
    category: "dashAttack",
    move: "dash_attack",
    startup: 6,
    active: 4,
    recovery: 16,
    damage: 9,
    baseKnockback: 10,
    knockbackGrowth: 1.25,
    hitstop: 6,
    angleDeg: 25,
    shieldDamage: 7,
    shieldStunFrames: 10,
    hitboxWidth: 52,
    hitboxHeight: 32,
    hitboxOffsetX: 40,
    hitboxOffsetY: 44,
    groundedOnly: true,
  }),
  neutral_air: move({
    id: "neutral_air",
    label: "Neutral Air",
    category: "neutralAir",
    move: "neutral_air",
    startup: 4,
    active: 4,
    recovery: 14,
    damage: 5,
    baseKnockback: 6,
    knockbackGrowth: 1.1,
    hitstop: 4,
    angleDeg: 55,
    shieldDamage: 4,
    shieldStunFrames: 7,
    hitboxWidth: 44,
    hitboxHeight: 36,
    hitboxOffsetX: 24,
    hitboxOffsetY: 44,
    airborneOnly: true,
  }),
  forward_air: move({
    id: "forward_air",
    label: "Forward Air",
    category: "forwardAir",
    move: "forward_air",
    startup: 5,
    active: 4,
    recovery: 16,
    damage: 7,
    baseKnockback: 8,
    knockbackGrowth: 1.15,
    hitstop: 5,
    angleDeg: 35,
    shieldDamage: 5,
    shieldStunFrames: 8,
    hitboxWidth: 48,
    hitboxHeight: 32,
    hitboxOffsetX: 36,
    hitboxOffsetY: 44,
    airborneOnly: true,
  }),
  back_air: move({
    id: "back_air",
    label: "Back Air",
    category: "backAir",
    move: "back_air",
    startup: 5,
    active: 4,
    recovery: 16,
    damage: 8,
    baseKnockback: 9,
    knockbackGrowth: 1.18,
    hitstop: 5,
    angleDeg: 145,
    shieldDamage: 5,
    shieldStunFrames: 8,
    hitboxWidth: 48,
    hitboxHeight: 32,
    hitboxOffsetX: -36,
    hitboxOffsetY: 44,
    airborneOnly: true,
  }),
  up_air: move({
    id: "up_air",
    label: "Up Air",
    category: "upAir",
    move: "up_air",
    startup: 5,
    active: 5,
    recovery: 18,
    damage: 8,
    baseKnockback: 9,
    knockbackGrowth: 1.2,
    hitstop: 6,
    angleDeg: 85,
    shieldDamage: 6,
    shieldStunFrames: 9,
    hitboxWidth: 40,
    hitboxHeight: 44,
    hitboxOffsetX: 0,
    hitboxOffsetY: 56,
    airborneOnly: true,
  }),
  down_air: move({
    id: "down_air",
    label: "Down Air",
    category: "downAir",
    move: "down_air",
    startup: 4,
    active: 5,
    recovery: 20,
    damage: 9,
    baseKnockback: 8,
    knockbackGrowth: 1.15,
    hitstop: 6,
    angleDeg: -70,
    shieldDamage: 6,
    shieldStunFrames: 9,
    hitboxWidth: 40,
    hitboxHeight: 36,
    hitboxOffsetX: 0,
    hitboxOffsetY: 28,
    airborneOnly: true,
    landingLagOverride: 18,
  }),
  aerial_attack: move({
    id: "aerial_attack",
    label: "Neutral Air",
    category: "neutralAir",
    move: "aerial_attack",
    startup: 4,
    active: 4,
    recovery: 14,
    damage: 5,
    baseKnockback: 6,
    knockbackGrowth: 1.1,
    hitstop: 4,
    angleDeg: 55,
    shieldDamage: 4,
    shieldStunFrames: 7,
    hitboxWidth: 44,
    hitboxHeight: 36,
    hitboxOffsetX: 24,
    hitboxOffsetY: 44,
    airborneOnly: true,
  }),
  special_attack: move({
    id: "special_attack",
    label: "Neutral Special",
    category: "neutralSpecial",
    move: "special_attack",
    startup: 8,
    active: 4,
    recovery: 18,
    damage: 10,
    baseKnockback: 12,
    knockbackGrowth: 1.3,
    hitstop: 7,
    angleDeg: 25,
    shieldDamage: 8,
    shieldStunFrames: 12,
    hitboxWidth: 56,
    hitboxHeight: 40,
    hitboxOffsetX: 40,
    hitboxOffsetY: 44,
  }),
  side_special: move({
    id: "side_special",
    label: "Side Special",
    category: "sideSpecial",
    move: "side_special",
    startup: 10,
    active: 5,
    recovery: 20,
    damage: 12,
    baseKnockback: 14,
    knockbackGrowth: 1.35,
    hitstop: 8,
    angleDeg: 20,
    shieldDamage: 10,
    shieldStunFrames: 14,
    hitboxWidth: 60,
    hitboxHeight: 44,
    hitboxOffsetX: 44,
    hitboxOffsetY: 44,
  }),
  up_special: move({
    id: "up_special",
    label: "Up Special",
    category: "upSpecial",
    move: "up_special",
    startup: 9,
    active: 6,
    recovery: 22,
    damage: 11,
    baseKnockback: 13,
    knockbackGrowth: 1.32,
    hitstop: 8,
    angleDeg: 75,
    shieldDamage: 9,
    shieldStunFrames: 13,
    hitboxWidth: 48,
    hitboxHeight: 52,
    hitboxOffsetX: 0,
    hitboxOffsetY: 56,
  }),
  down_special: move({
    id: "down_special",
    label: "Down Special",
    category: "downSpecial",
    move: "down_special",
    startup: 8,
    active: 5,
    recovery: 20,
    damage: 9,
    baseKnockback: 10,
    knockbackGrowth: 1.25,
    hitstop: 7,
    angleDeg: -45,
    shieldDamage: 8,
    shieldStunFrames: 12,
    hitboxWidth: 52,
    hitboxHeight: 36,
    hitboxOffsetX: 28,
    hitboxOffsetY: 32,
  }),
  multi_hit_special: move({
    id: "multi_hit_special",
    label: "Multi-Hit Special",
    category: "neutralSpecial",
    move: "multi_hit_special",
    startup: 6,
    active: 12,
    recovery: 16,
    damage: 4,
    baseKnockback: 3,
    knockbackGrowth: 1.05,
    hitstop: 3,
    angleDeg: 40,
    shieldDamage: 3,
    shieldStunFrames: 5,
    hitboxWidth: 48,
    hitboxHeight: 36,
    hitboxOffsetX: 32,
    hitboxOffsetY: 44,
    multiHit: true,
    hitIntervalFrames: 4,
    canHitSameTargetAgain: true,
  }),
  grab: move({
    id: "grab",
    label: "Grab",
    category: "grab",
    move: "grab",
    startup: 4,
    active: 3,
    recovery: 18,
    damage: 0,
    baseKnockback: 0,
    knockbackGrowth: 0,
    hitstop: 0,
    angleDeg: 0,
    shieldDamage: 0,
    shieldStunFrames: 0,
    hitboxWidth: 36,
    hitboxHeight: 40,
    hitboxOffsetX: 28,
    hitboxOffsetY: 44,
    groundedOnly: true,
  }),
  pummel: move({
    id: "pummel",
    label: "Pummel",
    category: "pummel",
    move: "pummel",
    startup: 2,
    active: 1,
    recovery: 8,
    damage: 2,
    baseKnockback: 0,
    knockbackGrowth: 0,
    hitstop: 2,
    angleDeg: 0,
    shieldDamage: 0,
    shieldStunFrames: 0,
    hitboxWidth: 24,
    hitboxHeight: 24,
    hitboxOffsetX: 20,
    hitboxOffsetY: 44,
  }),
  throw_forward: move({
    id: "throw_forward",
    label: "Forward Throw",
    category: "forwardThrow",
    move: "throw_forward",
    startup: 8,
    active: 2,
    recovery: 14,
    damage: 8,
    baseKnockback: 12,
    knockbackGrowth: 1.1,
    hitstop: 6,
    angleDeg: 30,
    shieldDamage: 0,
    shieldStunFrames: 0,
    hitboxWidth: 0,
    hitboxHeight: 0,
    hitboxOffsetX: 0,
    hitboxOffsetY: 0,
  }),
  throw_back: move({
    id: "throw_back",
    label: "Back Throw",
    category: "backThrow",
    move: "throw_back",
    startup: 8,
    active: 2,
    recovery: 14,
    damage: 9,
    baseKnockback: 13,
    knockbackGrowth: 1.12,
    hitstop: 6,
    angleDeg: 150,
    shieldDamage: 0,
    shieldStunFrames: 0,
    hitboxWidth: 0,
    hitboxHeight: 0,
    hitboxOffsetX: 0,
    hitboxOffsetY: 0,
  }),
  throw_up: move({
    id: "throw_up",
    label: "Up Throw",
    category: "upThrow",
    move: "throw_up",
    startup: 8,
    active: 2,
    recovery: 14,
    damage: 7,
    baseKnockback: 11,
    knockbackGrowth: 1.08,
    hitstop: 6,
    angleDeg: 85,
    shieldDamage: 0,
    shieldStunFrames: 0,
    hitboxWidth: 0,
    hitboxHeight: 0,
    hitboxOffsetX: 0,
    hitboxOffsetY: 0,
  }),
  throw_down: move({
    id: "throw_down",
    label: "Down Throw",
    category: "downThrow",
    move: "throw_down",
    startup: 8,
    active: 2,
    recovery: 14,
    damage: 6,
    baseKnockback: 8,
    knockbackGrowth: 1.05,
    hitstop: 5,
    angleDeg: -60,
    shieldDamage: 0,
    shieldStunFrames: 0,
    hitboxWidth: 0,
    hitboxHeight: 0,
    hitboxOffsetX: 0,
    hitboxOffsetY: 0,
  }),
  spot_dodge: move({
    id: "spot_dodge",
    label: "Spot Dodge",
    category: "spotDodge",
    move: "spot_dodge",
    startup: 2,
    active: 8,
    recovery: 10,
    damage: 0,
    baseKnockback: 0,
    knockbackGrowth: 0,
    hitstop: 0,
    angleDeg: 0,
    shieldDamage: 0,
    shieldStunFrames: 0,
    hitboxWidth: 0,
    hitboxHeight: 0,
    hitboxOffsetX: 0,
    hitboxOffsetY: 0,
    groundedOnly: true,
  }),
  roll: move({
    id: "roll",
    label: "Roll",
    category: "roll",
    move: "roll",
    startup: 3,
    active: 10,
    recovery: 12,
    damage: 0,
    baseKnockback: 0,
    knockbackGrowth: 0,
    hitstop: 0,
    angleDeg: 0,
    shieldDamage: 0,
    shieldStunFrames: 0,
    hitboxWidth: 0,
    hitboxHeight: 0,
    hitboxOffsetX: 0,
    hitboxOffsetY: 0,
    groundedOnly: true,
  }),
  air_dodge: move({
    id: "air_dodge",
    label: "Air Dodge",
    category: "airDodge",
    move: "air_dodge",
    startup: 2,
    active: 12,
    recovery: 18,
    damage: 0,
    baseKnockback: 0,
    knockbackGrowth: 0,
    hitstop: 0,
    angleDeg: 0,
    shieldDamage: 0,
    shieldStunFrames: 0,
    hitboxWidth: 0,
    hitboxHeight: 0,
    hitboxOffsetX: 0,
    hitboxOffsetY: 0,
    airborneOnly: true,
  }),
  dodge: move({
    id: "dodge",
    label: "Spot Dodge",
    category: "spotDodge",
    move: "dodge",
    startup: 2,
    active: 8,
    recovery: 10,
    damage: 0,
    baseKnockback: 0,
    knockbackGrowth: 0,
    hitstop: 0,
    angleDeg: 0,
    shieldDamage: 0,
    shieldStunFrames: 0,
    hitboxWidth: 0,
    hitboxHeight: 0,
    hitboxOffsetX: 0,
    hitboxOffsetY: 0,
  }),
};

export function getCatalogMove(moveId: string): CombatMoveData | null {
  return DEFAULT_MOVE_CATALOG[moveId] ?? null;
}

export function listCatalogMoveIds(): string[] {
  return Object.keys(DEFAULT_MOVE_CATALOG);
}
