import type { DefaultFighterId } from "../defaultFighters.js";
import type { MoveSlot, SkillCeiling } from "./universalMoveSchema.js";

/** Original move display names per fighter — one full universal moveset each. */
export const FIGHTER_MOVE_NAMES: Record<DefaultFighterId, Record<MoveSlot, string>> = {
  "ember-vale": {
    neutralAttack: "Cinder Jab",
    sideAttack: "Ember Cross",
    upAttack: "Rising Flare",
    downAttack: "Ash Sweep",
    neutralAir: "Flame Spin",
    forwardAir: "Burning Heel",
    backAir: "Backdraft Kick",
    upAir: "Spark Upper",
    downAir: "Meteor Ember",
    neutralSpecial: "Cinder Shot",
    sideSpecial: "Flame Dash",
    upSpecial: "Phoenix Step",
    downSpecial: "Heat Guard",
    grab: "Ember Grab",
    throwForward: "Flame Toss",
    throwBack: "Back Burn",
    throwUp: "Sky Toss",
    throwDown: "Ground Ember",
    super: "Solar Burst",
  },
  "rook-ironside": {
    neutralAttack: "Iron Knuckle",
    sideAttack: "Hammer Step",
    upAttack: "Pillar Upper",
    downAttack: "Ground Breaker",
    neutralAir: "Anvil Spin",
    forwardAir: "Boulder Fist",
    backAir: "Reverse Shoulder",
    upAir: "Rising Plate",
    downAir: "Drop Weight",
    neutralSpecial: "Guarded Charge",
    sideSpecial: "Faultline Rush",
    upSpecial: "Iron Lift",
    downSpecial: "Anchor Stance",
    grab: "Iron Grip",
    throwForward: "Slam Toss",
    throwBack: "Reversal Throw",
    throwUp: "Plate Lift",
    throwDown: "Anvil Drop",
    super: "Titan Impact",
  },
  "juno-spark": {
    neutralAttack: "Static Tap",
    sideAttack: "Flash Kick",
    upAttack: "Circuit Pop",
    downAttack: "Low Voltage",
    neutralAir: "Spark Wheel",
    forwardAir: "Flash Needle",
    backAir: "Reverse Arc",
    upAir: "Thunder Flick",
    downAir: "Bolt Drop",
    neutralSpecial: "Spark Shot",
    sideSpecial: "Blink Strike",
    upSpecial: "Volt Ladder",
    downSpecial: "Charge Step",
    grab: "Static Grab",
    throwForward: "Arc Toss",
    throwBack: "Reverse Spark",
    throwUp: "Lift Arc",
    throwDown: "Ground Zap",
    super: "Lightning Bloom",
  },
  "kaia-windrow": {
    neutralAttack: "Palm Breeze",
    sideAttack: "Sash Slash",
    upAttack: "Updraft Palm",
    downAttack: "Low Current",
    neutralAir: "Cyclone Turn",
    forwardAir: "Gale Spear",
    backAir: "Tailwind Kick",
    upAir: "Sky Spiral",
    downAir: "Falling Current",
    neutralSpecial: "Wind Ring",
    sideSpecial: "Sash Glide",
    upSpecial: "Lift Current",
    downSpecial: "Air Brake",
    grab: "Sash Grab",
    throwForward: "Gale Toss",
    throwBack: "Backdraft",
    throwUp: "Spiral Toss",
    throwDown: "Current Slam",
    super: "Tempest Bloom",
  },
  "nix-calder": {
    neutralAttack: "Frost Palm",
    sideAttack: "Glacier Hook",
    upAttack: "Ice Shelf",
    downAttack: "Cold Snap",
    neutralAir: "Hail Turn",
    forwardAir: "Frozen Hammer",
    backAir: "Ice Backhand",
    upAir: "Shard Lift",
    downAir: "Permafrost Drop",
    neutralSpecial: "Ice Shard",
    sideSpecial: "Glacier Slide",
    upSpecial: "Frost Rise",
    downSpecial: "Chill Field",
    grab: "Frost Grip",
    throwForward: "Ice Toss",
    throwBack: "Shard Back",
    throwUp: "Shelf Lift",
    throwDown: "Freeze Drop",
    super: "Absolute Zero",
  },
  "orion-vell": {
    neutralAttack: "Orbit Jab",
    sideAttack: "Gravity Palm",
    upAttack: "Rising Orbit",
    downAttack: "Pull Sweep",
    neutralAir: "Ring Spin",
    forwardAir: "Comet Palm",
    backAir: "Reverse Orbit",
    upAir: "Star Lift",
    downAir: "Drop Well",
    neutralSpecial: "Gravity Well",
    sideSpecial: "Comet Step",
    upSpecial: "Orbit Rise",
    downSpecial: "Anchor Pulse",
    grab: "Orbit Grab",
    throwForward: "Comet Toss",
    throwBack: "Reverse Pull",
    throwUp: "Star Toss",
    throwDown: "Well Slam",
    super: "Event Horizon",
  },
  "vesper-nyx": {
    neutralAttack: "Void Tap",
    sideAttack: "Rift Cut",
    upAttack: "Phase Upper",
    downAttack: "Shadow Slip",
    neutralAir: "Null Spin",
    forwardAir: "Rift Needle",
    backAir: "Fade Kick",
    upAir: "Eclipse Flick",
    downAir: "Void Drop",
    neutralSpecial: "Rift Seed",
    sideSpecial: "Phase Step",
    upSpecial: "Vanish Rise",
    downSpecial: "Afterimage Trap",
    grab: "Void Grab",
    throwForward: "Rift Toss",
    throwBack: "Fade Back",
    throwUp: "Phase Toss",
    throwDown: "Null Slam",
    super: "Midnight Divide",
  },
};

export const FIGHTER_SKILL_PROFILE: Record<
  DefaultFighterId,
  { floor: "beginner" | "intermediate" | "advanced"; ceiling: SkillCeiling }
> = {
  "ember-vale": { floor: "beginner", ceiling: "medium" },
  "rook-ironside": { floor: "beginner", ceiling: "medium" },
  "nix-calder": { floor: "beginner", ceiling: "medium" },
  "kaia-windrow": { floor: "intermediate", ceiling: "medium" },
  "orion-vell": { floor: "intermediate", ceiling: "high" },
  "juno-spark": { floor: "advanced", ceiling: "high" },
  "vesper-nyx": { floor: "advanced", ceiling: "high" },
};

export const BEAM_SUPER_FIGHTERS: DefaultFighterId[] = [
  "ember-vale",
  "rook-ironside",
  "juno-spark",
  "kaia-windrow",
  "nix-calder",
  "orion-vell",
  "vesper-nyx",
];

export const SUPER_ENERGY_KIND: Partial<Record<DefaultFighterId, "beam" | "orb" | "wave" | "shockwave">> = {
  "ember-vale": "beam",
  "rook-ironside": "shockwave",
  "juno-spark": "beam",
  "kaia-windrow": "wave",
  "nix-calder": "beam",
  "orion-vell": "orb",
  "vesper-nyx": "beam",
};
