name = "anime-aggressors-worker"
main = "src/index.ts"
compatibility_date = "2024-10-01"

[vars]
CORS_ORIGIN = "*"

[[r2_buckets]]
binding = "PROFILES"
bucket_name = "anime-aggressors-profiles"

[[r2_buckets]]
binding = "LEADERBOARDS"
bucket_name = "anime-aggressors-leaderboards"
