"""v9 review packet. Contact shots use combat cameras and action-line staging."""
from __future__ import annotations

# label, action, frame, preset, silhouette, grayscale, outline, aim, pair, vfx, emission_off
PACKET = (
    ("select_preview", "idle", 1, "FRONT_3Q", False, False, True, "", False, False, False),
    ("front", "", 1, "FRONT_ORTHO", False, False, False, "", False, False, False),
    ("front_3q", "", 1, "FRONT_3Q", False, False, False, "", False, False, False),
    ("front_3q_color", "idle", 1, "FRONT_3Q", False, False, False, "", False, False, False),
    ("front_3q_grayscale", "idle", 1, "FRONT_3Q", False, True, False, "", False, False, True),
    ("side", "", 1, "SIDE", False, False, False, "", False, False, False),
    ("back", "", 1, "BACK", False, False, False, "", False, False, False),
    ("gameplay_scale", "idle", 1, "GAMEPLAY_LEFT", False, False, False, "", False, False, False),
    ("gameplay_color", "idle", 1, "GAMEPLAY_LEFT", False, False, False, "", False, False, False),
    ("gameplay_grayscale", "idle", 1, "GAMEPLAY_LEFT", False, True, False, "", False, False, True),
    ("emission_off", "idle", 1, "FRONT_ORTHO", False, False, False, "", False, False, True),
    ("mask_detail", "idle", 1, "DETAIL_HEAD", False, False, True, "head", False, False, False),
    ("head_detail", "idle", 1, "DETAIL_HEAD", False, False, True, "head", False, False, False),
    ("glove_fist", "idle", 1, "DETAIL_HANDS", False, False, False, "glove", False, False, False),
    ("glove_open", "personality_idle", 8, "DETAIL_HANDS", False, False, False, "glove_open", False, False, False),
    ("glove_guard", "charged_idle", 12, "DETAIL_HANDS", False, False, False, "glove_guard", False, False, False),
    ("glove_cast", "signature_lane_finisher", 16, "DETAIL_HANDS", False, False, False, "glove_cast", False, False, False),
    ("glove_fist_silhouette", "idle", 1, "DETAIL_HANDS", True, False, False, "glove", False, False, False),
    ("glove_open_silhouette", "personality_idle", 8, "DETAIL_HANDS", True, False, False, "glove_open", False, False, False),
    ("boot_detail", "idle", 1, "DETAIL_FEET", False, False, False, "boot", False, False, False),
    ("boot_silhouette", "idle", 1, "DETAIL_FEET", True, False, False, "boot", False, False, False),
    ("costume_detail", "idle", 1, "DETAIL_COSTUME", False, False, False, "costume", False, False, False),
    ("grayscale_values", "idle", 1, "FRONT_ORTHO", False, True, False, "", False, False, True),
    ("silhouette_idle", "idle", 1, "SILHOUETTE", True, False, False, "", False, False, False),
    ("silhouette_super", "signature_lane_finisher", 16, "SILHOUETTE", True, False, False, "", False, False, False),
    ("idle", "idle", 1, "FRONT_3Q", False, False, False, "", False, False, False),
    ("personality_idle", "personality_idle", 8, "FRONT_3Q", False, False, False, "", False, False, False),
    ("walk", "walk", 8, "FRONT_3Q", False, False, False, "", False, False, False),
    ("walk_f0", "walk", 4, "SIDE", False, False, False, "", False, False, False),
    ("walk_f1", "walk", 8, "SIDE", False, False, False, "", False, False, False),
    ("walk_f2", "walk", 12, "SIDE", False, False, False, "", False, False, False),
    ("walk_f3", "walk", 16, "SIDE", False, False, False, "", False, False, False),
    ("run", "run", 6, "GAMEPLAY_LEFT", False, False, False, "", False, False, False),
    ("run_f0", "run", 3, "SIDE", False, False, False, "", False, False, False),
    ("run_f1", "run", 6, "SIDE", False, False, False, "", False, False, False),
    ("run_f2", "run", 9, "SIDE", False, False, False, "", False, False, False),
    ("run_f3", "run", 12, "SIDE", False, False, False, "", False, False, False),
    ("dash", "dash", 4, "GAMEPLAY_LEFT", False, False, False, "", False, False, False),
    ("charge_0_off", "idle", 1, "FRONT_3Q", False, False, False, "", False, False, True),
    ("charge_0_silhouette", "idle", 1, "SILHOUETTE", True, False, False, "", False, False, False),
    ("charge_100_off", "charged_idle", 12, "FRONT_3Q", False, False, False, "", False, False, True),
    ("charge_100_silhouette", "charged_idle", 12, "SILHOUETTE", True, False, False, "", False, False, False),
    ("charge_100_on", "charged_idle", 12, "FRONT_3Q", False, False, False, "", False, True, False),
    ("heavy_anticipation", "heavy", 4, "FRONT_3Q", False, False, False, "pair", True, False, False),
    ("heavy_precontact", "heavy", 8, "FRONT_3Q", False, False, False, "pair", True, False, False),
    ("heavy_contact_off", "heavy", 11, "FRONT_3Q", False, False, False, "pair", True, False, False),
    ("heavy_contact_grayscale", "heavy", 11, "FRONT_3Q", False, True, False, "pair", True, False, True),
    ("heavy_contact_on", "heavy", 11, "FRONT_3Q", False, False, False, "pair", True, True, False),
    ("heavy_contact_pair_off", "heavy", 11, "FRONT_3Q", False, False, False, "pair", True, False, False),
    ("heavy_contact_pair_debug", "heavy", 11, "FRONT_3Q", False, False, False, "pair_debug", True, False, False),
    ("heavy_contact_pair_on", "heavy", 11, "FRONT_3Q", False, False, False, "pair", True, True, False),
    ("follow_through", "heavy", 16, "FRONT_3Q", False, False, False, "pair", True, False, False),
    ("heavy_follow", "heavy", 16, "FRONT_3Q", False, False, False, "pair", True, False, False),
    ("hurt_peak", "hurt_heavy", 6, "FRONT_3Q", False, False, False, "", False, False, False),
    ("hurt_peak_no_knockback", "hurt_heavy", 6, "FRONT_3Q", False, False, False, "", False, False, False),
    ("launch_start", "hurt_heavy", 10, "FRONT_3Q", False, False, False, "", False, False, False),
    ("super_off", "signature_lane_finisher", 16, "FRONT_3Q", False, False, False, "", False, False, True),
    ("super_silhouette", "signature_lane_finisher", 16, "SILHOUETTE", True, False, False, "", False, False, False),
    ("super_on", "signature_lane_finisher", 16, "FRONT_3Q", False, False, False, "", False, True, False),
    ("clash_start", "clash_lock", 2, "FRONT_3Q", False, False, False, "pair", True, False, False),
    ("clash_lock_off", "clash_lock", 12, "FRONT_3Q", False, False, False, "pair", True, False, False),
    ("clash_lock", "clash_lock", 12, "FRONT_3Q", False, False, False, "pair", True, False, False),
    ("clash_lock_on", "clash_lock", 12, "FRONT_3Q", False, False, False, "pair", True, True, False),
    ("clash_push", "clash_lock", 16, "FRONT_3Q", False, False, False, "pair", True, False, False),
    ("clash_win", "clash_lock", 20, "FRONT_3Q", False, False, False, "pair", True, False, False),
    ("clash_lose", "clash_lock", 8, "FRONT_3Q", False, False, False, "pair", True, False, False),
    ("KO", "ko", 12, "FRONT_3Q", False, False, False, "", False, False, False),
    ("attachment_stress", "hurt_heavy", 6, "FRONT_3Q", False, False, False, "", False, False, False),
)

REQUIRED_SHOTS = tuple(row[0] for row in PACKET)

ROSTER_SHEETS = (
    "select_lineup",
    "color_lineup",
    "grayscale_lineup",
    "silhouettes",
    "idle_silhouettes",
    "masks",
    "gloves",
    "glove_silhouettes",
    "boots",
    "boot_silhouettes",
    "hero_features",
    "idle_identities",
    "locomotion_strips",
    "heavy_pairs",
    "heavy_contact_grid",
    "hurt_peaks",
    "hurt_grid",
    "charge_transformation",
    "charge_compare",
    "supers",
    "super_silhouettes",
    "clash_presets",
    "clash_grid",
    "value_groups",
    "attachment_stress",
)

STRESS_SHOTS = (
    ("idle", "idle", 1),
    ("dash", "dash", 4),
    ("heavy_contact", "heavy", 11),
    ("hurt_heavy", "hurt_heavy", 6),
    ("clash_lock", "clash_lock", 12),
)
