namespace AnimeAggressors
{
    public enum FighterState
    {
        Idle,
        Walk,
        Run,
        Jump,
        DoubleJump,
        Fall,
        FastFall,
        Land,
        AttackStartup,
        AttackActive,
        AttackRecovery,
        ShieldHold,
        ShieldStun,
        ShieldBreak,
        GrabStartup,
        GrabActive,
        GrabWhiff,
        GrabHold,
        ThrowRelease,
        AuraCharge,
        AuraReady,
        AuraBurstStartup,
        AuraBurstActive,
        AuraBurstRecovery,
        Hitstun,
        Launched,
        Dodge,
    }
}
