name: Deploy Anime Aggressors to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        cd apps/web
        npm install
        
    - name: Build Anime Aggressors
      run: |
        cd apps/web
        npm run build
      env:
        NODE_ENV: production
        
    - name: Prepare deployment
      run: |
        # Remove README.md to prevent it from being served
        rm -f README.md
        rm -f *.md
        
        # Copy built files to root
        cp -r apps/web/dist/* .
        
        # Ensure index.html exists
        if [ ! -f index.html ]; then
          echo "Creating fallback index.html"
          echo '<!DOCTYPE html><html><head><title>Anime Aggressors</title></head><body><h1>Game Loading...</h1></body></html>' > index.html
        fi
        
        # List files for debugging
        echo "Files in deployment directory:"
        ls -la
        
    - name: Upload build artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
