import type { PlayerState } from "../../src/types.js";
import { createDefaultAuraState } from "../../src/aura/auraTypes.js";
import { defaultMovementState } from "../../src/movement/movementTypes.js";

/** Minimal PlayerState for game-core unit tests. */
export function stubPlayer(overrides: Partial<PlayerState> = {}): PlayerState {
  return {
    id: 0,
    characterId: "ember",
    fighterName: "Test",
    fighterSize: "medium",
    fighterColor: "red",
    elementEffect: "burn",
    burnFramesRemaining: 0,
    slowFramesRemaining: 0,
    slowMultiplierFp: 100,
    airDriftBonusFrames: 0,
    x: 0,
    y: 0,
    vx: 0,
    vy: 0,
    facing: 1,
    damage: 0,
    stocks: 3,
    staminaHp: 0,
    maxStaminaHp: 0,
    score: 0,
    teamId: 0,
    actionState: "idle",
    actionFrame: 0,
    hitstunFrames: 0,
    shieldHealth: 100,
    jumpsRemaining: 2,
    jumpsUsed: 0,
    jumpHoldFrames: 0,
    wasJumpHeld: false,
    onGround: true,
    invulnFrames: 0,
    coyoteFrames: 0,
    jumpBufferFrames: 0,
    fastFalling: false,
    currentMoveId: "none",
    hitVictimsThisMove: [],
    currentPlatformId: "main",
    dropThroughFrames: 0,
    ignoredPlatformId: "",
    movementState: defaultMovementState(),
    dashFrames: 0,
    jumpSquatFrames: 0,
    jumpShortHop: false,
    landingLagFrames: 0,
    ledgeStateFrames: 0,
    grabbedLedgeId: "",
    ledgeCooldownFrames: 0,
    recoveryUsed: false,
    aura: createDefaultAuraState(),
    ...overrides,
  };
}
